// Scans the map-event text dump (data-import/source/MapEvents/EventTextDump.txt, synced from
// the game project's EventExporter output - see syncData.ts) to find where trainers are fought
// and where items can be picked up, so trainer/item pages can show a "found on" location.
//
// The dump is a flat, strictly sequential list of maps/events/commands (RPG Maker XP editor
// dump format), so a trainer/item reference is located by remembering the most recently seen
// "Map ID:"/"Event Name:" header while scanning line by line.
import { readFileSync, existsSync } from "node:fs";
import { join } from "node:path";
import { loadMapLocationNames } from "./mapMetadata.ts";
import type { MapLocationRef, ItemLocationRef } from "./dataModel.ts";

const DUMP_PATH = join(import.meta.dirname, "source", "MapEvents", "EventTextDump.txt");

const MAP_ID_RE = /^Map ID: (\d+)/;
const EVENT_NAME_RE = /^Event Name: (.+)/;
// TrainerBattle.start(:TRAINER_TYPE, "Name"[, rematchNumber]) - matches parseTrainers.ts's
// id = [trainerType, name, disambiguator].filter(Boolean).join("-") exactly.
const TRAINER_BATTLE_RE = /TrainerBattle\.start\(:(\w+),\s*"([^"]+)"(?:,\s*(\d+))?\)/;
const ITEM_BALL_RE = /pbItemBall\(:(\w+)/; // ground items and hidden (Itemfinder) items alike
const RECEIVE_ITEM_RE = /pbReceiveItem\(:(\w+)/; // items given by an NPC
const PICK_BERRY_RE = /pbPickBerry\(:(\w+)/; // berry trees
const MCR_RE = /pbMCR\("(\w+)"/; // rare "cinematic receive" key items
// Poké Mart shop stock: "@>Script: pbPokemonMart([" opens the call, one or more ":ITEM_ID"
// symbols follow across several continuation lines ("  :       :   :POTION, :SUPERPOTION,"),
// and "])" closes it - always on its own line in this dump (verified: 201/202 pbPokemonMart
// occurrences open this way, the one exception is a doc comment mentioning the function name,
// which never matches SHOP_START_RE since it has no "([" ).
const SHOP_START_RE = /pbPokemonMart\(\[/;
const SHOP_END_RE = /\]\)/;
const SHOP_ITEM_RE = /:(\w+)/g;

// Leftover, unused default Pokémon Essentials demo content (Lappet Town, Cedolan City,
// Route 1-8, Battle Frontier, Safari Zone, Berth/Faraday Island, ...) plus a few stray
// developer test maps, none of which are part of the actual shipped game. This is deliberately
// an explicit id set rather than an id range or a name match: real Velmora maps are interspersed
// *within* the 001-075 demo block (ids 22, 32, 33, 42, 43, 48), and demo location names like
// "Route 3"/"Route 4" are reused verbatim by real, later maps elsewhere (e.g. the real Route 3
// is map 156) - both a range and a name filter would misclassify those.
export const EXCLUDED_MAP_IDS = new Set<number>([
  // Default Essentials demo region (map 022, 032, 033, 042, 043, 048 are real Velmora maps
  // interspersed among these ids and are intentionally NOT included here).
  ...Array.from({ length: 75 }, (_, i) => i + 1).filter((id) => ![22, 32, 33, 42, 43, 48].includes(id)),
  83, // stray leftover duplicate of the demo's "Route 1"
  203, // "Nicht verwendet Test Map leuchtende Kristalle" - explicitly marked unused by the devs
  288, // "VM-Testmap" - developer test map
]);

export interface MapLocationsResult {
  trainerLocations: Map<string, MapLocationRef[]>;
  itemLocations: Map<string, ItemLocationRef[]>;
}

function addLocation<T extends { mapId: string }>(map: Map<string, T[]>, id: string, ref: T, dedupeKey: (r: T) => string) {
  const list = map.get(id);
  if (!list) {
    map.set(id, [ref]);
    return;
  }
  if (!list.some((r) => dedupeKey(r) === dedupeKey(ref))) list.push(ref);
}

export function parseMapLocations(): MapLocationsResult {
  const trainerLocations = new Map<string, MapLocationRef[]>();
  const itemLocations = new Map<string, ItemLocationRef[]>();
  // The dump is manually (re-)generated by the user via an external export tool and isn't
  // always present - skip quietly rather than error, same as the rest of the sync pipeline.
  if (!existsSync(DUMP_PATH)) return { trainerLocations, itemLocations };

  const locationNames = loadMapLocationNames();
  const lines = readFileSync(DUMP_PATH, "utf-8").split("\n");

  let mapId = "";
  let locationName = "";
  let eventName = "";
  let mapExcluded = true;
  let inShop = false;

  for (const line of lines) {
    const mapMatch = MAP_ID_RE.exec(line);
    if (mapMatch) {
      mapId = mapMatch[1];
      locationName = locationNames.get(mapId) ?? mapId;
      mapExcluded = EXCLUDED_MAP_IDS.has(Number(mapId));
      inShop = false; // a shop block never spans a map boundary; don't leak into the next map
      continue;
    }
    if (mapExcluded) continue;

    if (inShop) {
      for (const m of line.matchAll(SHOP_ITEM_RE)) {
        addLocation(itemLocations, m[1], { mapId, locationName, source: "shop" }, (r) => `${r.mapId}:${r.source}`);
      }
      if (SHOP_END_RE.test(line)) inShop = false;
      continue;
    }
    if (SHOP_START_RE.test(line)) {
      inShop = true;
      continue;
    }

    const eventMatch = EVENT_NAME_RE.exec(line);
    if (eventMatch) {
      eventName = eventMatch[1].trim();
      continue;
    }

    const trainerMatch = TRAINER_BATTLE_RE.exec(line);
    if (trainerMatch) {
      const [, trainerType, name, rematch] = trainerMatch;
      const id = [trainerType, name, rematch].filter(Boolean).join("-");
      addLocation(trainerLocations, id, { mapId, locationName }, (r) => r.mapId);
      continue;
    }

    const itemBallMatch = ITEM_BALL_RE.exec(line);
    if (itemBallMatch) {
      const source = eventName === "HiddenItem" ? "hidden" : "ground";
      addLocation(itemLocations, itemBallMatch[1], { mapId, locationName, source }, (r) => `${r.mapId}:${r.source}`);
      continue;
    }
    const receiveMatch = RECEIVE_ITEM_RE.exec(line);
    if (receiveMatch) {
      addLocation(itemLocations, receiveMatch[1], { mapId, locationName, source: "gift" }, (r) => `${r.mapId}:${r.source}`);
      continue;
    }
    const berryMatch = PICK_BERRY_RE.exec(line);
    if (berryMatch) {
      addLocation(itemLocations, berryMatch[1], { mapId, locationName, source: "berry" }, (r) => `${r.mapId}:${r.source}`);
      continue;
    }
    const mcrMatch = MCR_RE.exec(line);
    if (mcrMatch) {
      addLocation(itemLocations, mcrMatch[1], { mapId, locationName, source: "special" }, (r) => `${r.mapId}:${r.source}`);
    }
  }

  return { trainerLocations, itemLocations };
}
